version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork
    hostname: my-react-app

networks:
  mynetwork:
    driver: bridge
