version: '3'
services:
<<<<<<< HEAD
  frontend:
    build:
      context: ./qms-app  # adjust the path to your actual frontend location
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./qms-api  # adjust the path to your actual backend location
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - frontend
=======
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork
    hostname: my-react-app

networks:
  mynetwork:
    driver: bridge
>>>>>>> 78efdbede2d88e5124364fffd00b207b66cad6f4
